### ISSUE TITLE
export full calendar

### ISSUE THREAD

**Issue by nitin0708** [arshaw/fullcalendar#240]
Hi

How to export full calendar?

Thanks

Nitin

**Comment by espen** [comment]
1) "If you still can't find an answer, post your question on the StackOverflow fullcalendar tag. When entering a new question, make sure you tag it with fullcalendar." http://fullcalendar.io/wiki/Support/

2) $('#calendar').fullCalendar('clientEvents') will retrieve events.

Please close this issue.
