### ISSUE TITLE
JS error on sample instructions

### ISSUE THREAD

**Issue by timwis** [arshaw/fullcalendar#244]
I wrote a test case based on the sample instructions of the documentation and I'm getting a javascript error in the console.
`Uncaught TypeError: Cannot read property 'each' of null` on fullcalendar.js:5022

```html
<html>
  <head>
    <link rel='stylesheet' href='//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.3.2/fullcalendar.min.css' />
    <script src='//cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.min.js'></script>
    <script src='//cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.min.js'></script>
    <script src='//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.3.2/fullcalendar.js'></script>
    <style type="text/css">
      #calendar {
        width: 800px;
        height: 500px;
      }
    </style>
  </head>
  <body>
    <div id="calendar"></div>
    
    <script>
      $(document).ready(function() {
        $('#calendar').fullCalendar();
      });
    </script>
  </body>
</html>
```
On the page, it just renders the "today" and "< >" buttons and not the calendar (until I click "today"). If I switch to v2.3.1 of fullcalendar.js the error disappears and it works.

**Comment by espen** [comment]
Have you tried using jQuery 2? jQuery 3 is just alpha.

**Comment by timwis** [comment]
I've got to assume that was it, didn't want to leave this open. Thanks!
