### ISSUE TITLE
slotEventOverlap custom rendering question.

### ISSUE THREAD

**Issue by mcmatthew** [arshaw/fullcalendar#247]
```
slotEventOverlap

Determines if timed events in agenda view should visually overlap.

Boolean, default: true
When set to true (the default), events will overlap each other. At most half of each event will be obscured:
```

I'm needing to have a slot event overlap completely within another event.  For example, from 8am - 12pm, an event can be created that will identify what types of events can be booked into the slot.  When a user would book into the slot, the event would appear within the 'parent' slot.  Currently it overlaps, but only by 50% and the edges of the 'child' event stick out.  Is there any way to customize this to show inside completely?

I attempted to use background events, but I need to be able to put a description on the parent event to identify what can be booked there / what it's purpose is.  Currently it appears background events don't suppor this.  I also need the ability to create an event outside of this parent and render it without any overlapping.  Background events don't seem to have the ability to not overlap with normal events so I don't think this will work.

Can you provide some information that I might have missed in making this possible?  Any other ideas for accomplishing this?

Thanks

**Comment by espen** [comment]
Please see http://fullcalendar.io/wiki/Support/ and close this issue. Thanks.
