### ISSUE TITLE
Allow multiple BusinessHours

### ISSUE THREAD

**Issue by billmn** [arshaw/fullcalendar#261]
I had the need to set **multiple Business** Hours with different options for each day.

![schermata 2015-08-10 alle 12 10 32](https://cloud.githubusercontent.com/assets/779534/9168669/e0a4126c-3f58-11e5-929f-99658c3ee812.png)

Now this package doesn't support this feature but I've seen changes on this fork and it seems good:

Demo: http://eo14.com/static/fullcalendar/
Discussion: http://stackoverflow.com/a/30380267

Changes: https://github.com/dtmonterrey/fullcalendar/commit/d9848d0ae7d7dae0f0340c62ce38b8acc0d03b62

What about consider to use this implementation in the official package?

**Comment by espen** [comment]
See https://github.com/arshaw/fullcalendar/pull/237
