### ISSUE TITLE
FileFormat for week

### ISSUE THREAD

**Issue by shystruk** [arshaw/fullcalendar#262]
Hi all!

I need title format like this e.g. August 9 - 15 August, 2015.
For now I'm using format like this "MMMM D MMMM, YYYY" it works ok, but when we have another month they will duplicate e.g. August 30 August - September 5 September, 2015.

Could help me please choose correct titleFormat ?
Thank you!

**Comment by espen** [comment]
Please see http://fullcalendar.io/wiki/Support/ and close this issue, thanks.

FullCalendar uses Moment. http://fullcalendar.io/docs/utilities/date_formatting_string/
